name: Update S3 Firmware List

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-s3-firmware-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
      - name: Run fetch_s3_firmware_list.py
        run: |
          python scripts/fetch_s3_firmware_list.py
      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lists/download.tplinkcloud.com_all_keys.txt
          git commit -m "Update S3 firmware list $(date +'%Y%m%d')"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push
